### PR TITLE
Add support for dashboard query variables.

### LINKED ISSUE #80: Add support for query Dashboard Variables
Currently, when trying to use a  FlightSQL query as a dashboard variable there is no UI component to make the query.

A great example of this is when we want to filter by the host. We could use a query like:
```
SELECT DISTINCT host FROM cpu
```

Currently, there just shows a regex text box.
Screenshot 2023-02-01 at 12 45 15

### PR DESCRIPTION
**Pull request by TaoVonQi**
resolves #80

### CODE REVIEW

**Comment by helenosheaa** [comment]
thank you for submitting this!! I need to take some time to test it and once it's merged there is a separate submission process in getting the latest published to Grafana so I appreciate your patience

**Comment by titt** [comment]
Hello,
do you have any new about this PR ? I will be interested by this feature.
Best regards

**Comment by garylfowler** [comment]
@titt - have you tried the latest Grafana InfluxDB plug-in?  It now supports SQL and does have support for dashboard variables?

**Review by helenosheaa — APPROVED** [review]
Thanks for the contribution, apologies for the delay in getting this merged! I am going to work on a new release candidate for Grafana 

For future PRs new features would be best submitted to the Grafana [InfluxDB plugin ](https://github.com/grafana/grafana/tree/main/pkg/tsdb/influxdb) which has now incorporated FlightSQL support and is under active development.

**Pull request merged**
